<a href="https://colab.research.google.com/github/Sneha8126/ML-Projects/blob/main/Mobile_Recommend_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import pandas as pd
import numpy as np
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [61]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [62]:
df = pd.read_csv('/content/drive/MyDrive/mobile_recommendation_system_dataset.csv')

In [63]:
df.head()

,name,ratings,price,imgURL,corpus
0,"REDMI Note 12 Pro 5G (Onyx Black, 128 GB)",4.2,23999,https://rukminim2.flixcart.com/image/312/312/x...,Storage128 GBRAM6 SystemAndroid 12Processor T...
1,"OPPO F11 Pro (Aurora Green, 128 GB)",4.5,"₹20,999",https://rukminim2.flixcart.com/image/312/312/k...,Storage128 GBRAM6 GBExpandable Storage256GB S...
2,"REDMI Note 11 (Starburst White, 64 GB)",4.2,13149,https://rukminim2.flixcart.com/image/312/312/x...,Storage64 GBRAM4 SystemAndroid 11Processor Sp...
3,"OnePlus Nord CE 5G (Blue Void, 256 GB)",4.1,21999,https://rukminim2.flixcart.com/image/312/312/x...,Storage256 GBRAM12 SystemAndroid Q 11Processo...
4,"APPLE iPhone 13 mini (Blue, 128 GB)",4.6,3537,https://rukminim2.flixcart.com/image/312/312/k...,Storage128 SystemiOS 15Processor TypeA15 Bion...

In [64]:
df.shape

(2546, 5)

In [65]:
df.columns

Index(['name', 'ratings', 'price', 'imgURL', 'corpus'], dtype='object')

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2546 entries, 0 to 2545
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     2546 non-null   object
 1   ratings  2546 non-null   float64
 2   price    2546 non-null   object
 3   imgURL   2546 non-null   object
 4   corpus   2534 non-null   object
dtypes: float64(1), object(4)
memory usage: 99.6+ KB

In [67]:
df.isnull().sum()

name        0
ratings     0
price       0
imgURL      0
corpus     12
dtype: int64

In [68]:
df['corpus'] = df['corpus'].fillna('')

In [69]:
selected_features = ['corpus']

In [70]:
vectorizer = TfidfVectorizer(stop_words='english')
feature_vectors = vectorizer.fit_transform(df['corpus'])

In [71]:
similarity = cosine_similarity(feature_vectors)

In [73]:
mobile_name = input("Enter Mobile Name : ")

Enter Mobile Name : SAMSUNG Galaxy A04 (Green, 128 GB)

In [74]:
all_mobile_names = df['name'].tolist()

In [75]:
find_close_match = difflib.get_close_matches(
    mobile_name,
    all_mobile_names
)

In [76]:
close_match = find_close_match[0]

In [77]:
print(df.columns)

Index(['name', 'ratings', 'price', 'imgURL', 'corpus'], dtype='object')

In [78]:
index = df[df['name'] == close_match].index[0]

In [79]:
df = df.reset_index()

In [80]:
similarity_score = list(enumerate(similarity[index]))

In [81]:
sorted_similar_mobiles = sorted(
    similarity_score,
    key=lambda x: x[1],
    reverse=True
)

In [82]:
print("Recommended Mobiles:\n")

i = 1

for mobile in sorted_similar_mobiles:

    index = mobile[0]

    title = df[df.index == index]['name'].values[0]

    if i < 11:
        print(i, ".", title)
        i += 1

Recommended Mobiles:

1 . SAMSUNG Galaxy A04 (Green, 128 GB)
2 . SAMSUNG Galaxy A04 (Copper, 128 GB)
3 . SAMSUNG Galaxy A04 (Black, 128 GB)
4 . SAMSUNG Galaxy A04 (Copper, 64 GB)
5 . SAMSUNG Galaxy A04e (Copper, 128 GB)
6 . SAMSUNG Galaxy A04e (Light Blue, 128 GB)
7 . SAMSUNG Galaxy A04e (Copper, 64 GB)
8 . SAMSUNG Galaxy A13 (Blue, 128 GB)
9 . SAMSUNG Galaxy A12 (Blue, 128 GB)
10 . SAMSUNG Galaxy A13 (Black, 128 GB)

In [83]:
print("Recommended Mobiles\n")

i = 1

for mobile in sorted_similar_mobiles:

    index = mobile[0]

    row = df.iloc[index]

    if i <= 10:

        print("-----------------------------")
        print("Mobile :", row['name'])
        print("Rating :", row['ratings'])
        print("Price :", row['price'])
        print("-----------------------------")

        i += 1

Recommended Mobiles

-----------------------------
Mobile : SAMSUNG Galaxy A04 (Green, 128 GB)
Rating : 4.0
Price : 12999
-----------------------------
-----------------------------
Mobile : SAMSUNG Galaxy A04 (Copper, 128 GB)
Rating : 4.0
Price : 12799
-----------------------------
-----------------------------
Mobile : SAMSUNG Galaxy A04 (Black, 128 GB)
Rating : 4.0
Price : 11990
-----------------------------
-----------------------------
Mobile : SAMSUNG Galaxy A04 (Copper, 64 GB)
Rating : 4.4
Price : 11199
-----------------------------
-----------------------------
Mobile : SAMSUNG Galaxy A04e (Copper, 128 GB)
Rating : 4.1
Price : 11499
-----------------------------
-----------------------------
Mobile : SAMSUNG Galaxy A04e (Light Blue, 128 GB)
Rating : 4.1
Price : 11499
-----------------------------
-----------------------------
Mobile : SAMSUNG Galaxy A04e (Copper, 64 GB)
Rating : 4.2
Price : 9999
-----------------------------
-----------------------------
Mobile : SAMSUNG Galaxy A13 (Blue, 128 GB)
Rating : 4.1
Price : 15499
-----------------------------
-----------------------------
Mobile : SAMSUNG Galaxy A12 (Blue, 128 GB)
Rating : 4.2
Price : 17999
-----------------------------
-----------------------------
Mobile : SAMSUNG Galaxy A13 (Black, 128 GB)
Rating : 4.1
Price : 14999
-----------------------------

In [ ]:
print(df['name'].head(20))